version: '3'
services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - hello-world-app
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf

  hello-world-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"